### ISSUE TITLE
support redmine 5.x ?

### ISSUE THREAD

**Issue by altheali533** [koppen/redmine_github_hook#102]
my redmine is ver 5.0.4
Ruby31
bundler 2.4.3
can I run this plungs

**Comment by koppen** [comment]
Please investigate and report back. I am sure there are others who'd like to know.

**Comment by altheali533** [comment]
I find use mast version on redmine 5.0.4 ,it work !

**Comment by koppen** [comment]
Looks like we've actually had Redmine 5 compatibility since https://github.com/koppen/redmine_github_hook/pull/100 - I just forgot 😆 

I've added a comment to the README about it.
