### ISSUE TITLE
is payload['repository']['name'] evaluated?

### ISSUE THREAD

**Issue by letusfly85** [koppen/redmine_github_hook#67]
Hi, I installed this gem to our development redmine (ver. 2.4.1)
I want to use gitlab hook by using this plugin.

So, I got a problem.
When I tried to hook from gitlab 'https://<our-project>/redmine/github_hook',
redmine's production log put error message below.

```
  Parameters: {"before"=>"xxxxxxxxxxxxxxxxxxxxx", "after"=>"xxxxxxxxxxxxxxxxxxxxxx", "ref"=>"refs/heads/master", "user_id"=>2, "user_name"=>"xxxxx", "project_id"=>83, "repository"=>{"name"=>"our project", "url"=>"git@xx.xx.xx.xx:ourgroup/ourproject.git", "description"=>"", ,,,,,,,


Completed 500 Internal Server Error in 358.2ms

NoMethodError (undefined method `downcase' for 83:Fixnum):
  redmine_github_hook (2.1.0) app/services/github_hook/updater.rb:77:in `find_project'
```

I saw update.rb and wonder why 'project_id' is used by downcase method.

```ruby
    # Finds the Redmine project in the database based on the given project identifier
    def find_project
      identifier = get_identifier
      project = Project.find_by_identifier(identifier.downcase)
      raise ActiveRecord::RecordNotFound, "No project found with identifier '#{identifier}'" if project.nil?
      return project
    end
```

And I found get_project_name method's payload is not evaluated by this hook...

```ruby
    def get_project_name
      params[:project_id] || (payload['repository'] ? payload['repository']['name'] : nil)
    end
```

Is their any solutions?
If you know, please let me know.

**Comment by koppen** [comment]
What is the `"project_id"=>83` part of the payload?

By default, GitHub Hook assumes your GitHub repository name is the same as the project identifier in your Redmine installation - see [README](https://github.com/koppen/redmine_github_hook#3-connecting-github-to-redmine) for details.

You can specify the actual Redmine project identifier in the Post-Receive URL by using the format [redmine_url]/github_hook?project_id=[identifier] (for example http://redmine.example.com/github_hook?project_id=my_project).

**Comment by letusfly85** [comment]
Thanks, I will try it!
