### ISSUE TITLE
Linking Git user and Redmine users

### ISSUE THREAD

**Issue by jmcazaux** [koppen/redmine_github_hook#72]
When a smart commit is updating the issue (in our workflow, "fixes #125" will set the issue to "Develop"), the update appears to be done by "Anonymous".

Is it by design or is there a way to link the author of the commit with a Redmine user in order to see who actually triggered the change thru the commit.

Many thanks,
JM

**Comment by koppen** [comment]
Redmine Github Hook doesn't do anything in particular related to linking commits and issues, this is done by Redmine proper. Redmine Github Hook is used solely to make sure changes are fetched from the repository automatically.

I am not aware of any way to configure Redmine to do what youre asking, I'm afraid. You might be able to get help on [the Redmine boards](http://www.redmine.org/projects/redmine/boards), though.

**Comment by koppen** [comment]
Actually, I just spotted this at http://www.redmine.org/projects/redmine/wiki/RedmineRepositories#Repository-user-mapping:

> In the project -> settings -> repository there is a link called users (on the lower right).
> 
> That allows you to map users that have commits to the users in redmine. If the login name / email matches the mapping is automatic, otherwise you need to establish the map of repository users to redmine users.

**Comment by jmcazaux** [comment]
@koppen many thanks for pointing me in the right direction although this is not in remit of your plugin.

Thumbs up for the plugin and your help!
