### ISSUE TITLE
Clarify difference with Github's Redmine Webhook

### ISSUE THREAD

**Issue by kostajh** [koppen/redmine_github_hook#73]
The README for this project says:

> Note: Make sure you're adding a Webhook - which is what Redmine Github Hook expects. GitHub has some builtin Redmine integration; that's not what you're looking for.

Could you please clarify what the difference is between this project and Github's Redmine Webhook? As far as I can tell, they are both trying to solve the same problem -- updating the git repo on a server when GitHub is updated, and processing any issues with references in the commits.

**Comment by koppen** [comment]
Quite frankly, I don't remember. If the current incarnation of GitHubs Redmine integration works with Redmines sys/fetch_changesets, this project can be deprecated.

It didn't use to work and Redmine Github Hook has worked perfectly for my use, but I'd love to hear your experiences using the "proper" integration.

**Comment by kostajh** [comment]
@koppen thanks for the reply. Here's the [GitHub Redmine hook for reference](https://github.com/github/github-services/blob/master/lib/services/redmine.rb).

I wouldn't rush to deprecate this, as so far I'm unable to get GitHub's hook working, see github/github-services/issues/1051 - but in the long run it might make sense to consolidate efforts?

My experience so far:

feature | `koppen/redmine_github_hook` | `github-services/redmine`
----------|-----------------|-----------
Fetch commits from GitHub on push | yes | not working
Update issues in Redmine by processing references in commit messages | not working | not working

**Comment by koppen** [comment]
Thanks for investigating. I've been looking into this a bit as well. 

As far as I can tell, the standard Redmine `sys/fetch_changesets` way of doing things assumes the local repository has already been updated with changes from the remote repository. It investigates the local repository, importing the revisions there into the database.

Using GitHubs Redmine integration means this import into the database happens in the background, otherwise Redmine will perform the import whenever someone visits the repository page. Updating issues from commit messages probably also happens as part of this import.

What Redmine Github Hook does is actually fetch changes from the remote repository into the local one. It then triggers the import, which should trigger issues updating.

Does this sound about right?

**Comment by kostajh** [comment]
Thanks for looking into this @koppen. That *does* sound about right. I guess the problem I am having is that despite using both integrations, I'm not seeing git commits show up on the issue page, even when `refs #{some issue}` or `fixes #{some issue}` is used. And using the `fix/fixes` keyword doesn't actually close an issue. Is that the behavior you expect? I'm on Redmine 3.0.2 if that makes a difference.

**Comment by koppen** [comment]
As far as I can tell, that should be handled by Redmine. Redmine Github Hook is just a dumb `git pull && import changesets`.

For what it's worth, it works fine for us, albeit on Redmine 2.x. I don't remember if I had to do anything to make it work, but there are some configuration settings under Administration > Settings > Repositories that you might want to check looks correct.

**Comment by genachka** [comment]
@koppen 
Works for us in Redmine 2.5.x too (and thanks so much for making this!!). We're looking to move to Redmine 3.1.x shortly and wondering if you intend on testing and supporting that any time soon?

**Comment by koppen** [comment]
> We're looking to move to Redmine 3.1.x shortly and wondering if you intend on testing and supporting that any time soon?

@genachka, I have yet to move to 3.x myself, but I see no reason Github Hook 2.2 shouldn't work with Redmine 3.x. A quick test shows that it works just fine, at least on the surface.

The plan is definitely to support the Redmine 3.x series as well, feel free to open any issues if you encounter them.

**Comment by koppen** [comment]
@kostajh Do you need more from this issue, or can we close it?

**Comment by kostajh** [comment]
yes, thanks @koppen!
