### ISSUE TITLE
Refusing to fetch into current branch refs/heads/master of non-bare repository

### ISSUE THREAD

**Issue by devsmo** [koppen/redmine_github_hook#82]
I followed the documentation at this address:
http://www.redmine.org/projects/redmine/wiki/HowTo_keep_in_sync_your_git_repository_for_redmine

But I keep getting the following error:
> GithubHook: Command 'git fetch --prune origin "+refs/heads/*:refs/heads/*"' didn't exit properly. Full output: ["fatal: Refusing to fetch into current branch refs/heads/master of non-bare repository\n"]

I've found a similar ticket #11 but it didn't solve my issue.
What can I do to troubleshoot this?

**Comment by koppen** [comment]
Following the instructions at http://www.redmine.org/projects/redmine/wiki/HowTo_keep_in_sync_your_git_repository_for_redmine should set you up with a bare repository locally. The error message seems to indicate that you are trying to update a full-fledged, non-bare repository.

If you are just starting out having a repository in Redmine, I'd guess your best bet is to delete the local repository and recreate it with the `--bare` flag.

**Comment by devsmo** [comment]
Indeed, it worked with `git init --bare`

Thank you very much
