### ISSUE TITLE
Commits are not getting reflected on redmine portal

### ISSUE THREAD

**Issue by ivgituser** [koppen/redmine_github_hook#88]
Previously everything was working correctly, facing following issue from last month.
I did commits on repos by commit msg "refers #ticket_id  "  But I am not able to see commit reference under that ticket in redmine.

Received following errors in redmine logs.
################################## 
type\":\"User\",\"site_admin\":false}}", "project_id"=>"xyz", "repository_id"=>"abc"}
  Current user: anonymous
  GithubHook: Command 'git fetch origin' didn't exit properly. Full output: ["git: not found\n"]
  GithubHook: Redmine repository updated: abc (Git: 1.3ms, Redmine: 1.0ms)
Completed 200 OK in 7ms (Views: 0.2ms | ActiveRecord: 0.9ms)
########################################################3

**Comment by koppen** [comment]
> Command 'git fetch origin' didn't exit properly. Full output: ["git: not found\n"]

I don't know what exactly can cause git to respond with "not found" while doing a `git fetch origin`. My best guess is that it is actually your shell that's telling you it cannot find the git command.

You should verify that you can run git when logged in as the user running Redmine. In other words git needs to be installed _and in the PATH_ for whatever user Redmine is running as.

**Comment by koppen** [comment]
Closing due to lack of inactivity; presuming the issue has been fixed.
