### ISSUE TITLE
The release tag is not set after Ver.2.2.0.

### ISSUE THREAD

**Issue by takamat30** [koppen/redmine_github_hook#90]
I need a commit of ↓.
https://github.com/koppen/redmine_github_hook/commit/122ad0e26b7682c96631d0f1d5e06640cc2131a4

The release tag is not set after Ver.2.2.0.
Why is the release tag not set?
Is there a problem with commit after version 2.2.0?

**Comment by koppen** [comment]
You can install a version of the gem at the specific commit, if you really need to:

    gem "redmine_github_hook", :git => "https://github.com/koppen/redmine_github_hook.git", :ref => "122ad0e"

That said, we might be overdue for a release.

**Comment by koppen** [comment]
And v2.2.1 has been pushed: https://rubygems.org/gems/redmine_github_hook/versions/2.2.1
